### ISSUE TITLE
Config instant sleep vs vanilla

### ISSUE THREAD

**Issue by itsdeadfrosty** [GeheimagentNr1/EasierSleeping#7] opened 2023-05-13 19:50 UTC
instantly sleeping kinda sucks, and if youre only updating to the newest version for such a simple mod thats so lazy ill use something else

┆Issue is synchronized with this [Trello card](https://trello.com/c/DL1ekGMQ) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment] 2023-07-16 13:42
In some situations, I cannot prevent from instead sleep, for example, if 100 % or more than the vanilla percentage of the player are sleeping, because it would cause message chaos, if I trigger instead sleep. But I will try to prevent it in all situations, where it is possible.

**Comment by GeheimagentNr1** [comment] 2023-11-21 19:42
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>None</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Check with Minecraft 1.20.2, Forge 48.0.40, Mod version 2.1.3. If fully sleeping is not working.

**Comment by GeheimagentNr1** [comment] 2023-11-21 20:32
I just check, the way the mod works.  
Situation: 2 players on the server, sleeping percentage of the mod is 50% and playersSleepingPercentage gamerule 100%  
Case 1: Only one player is sleeping.  
            Result: The player has to sleep fully, before the night is skipped.  
Case 2: Both players are sleeping.  
            Result: The night is skipped instantly.  
  
Both cases are working as expected.  
  
As written before, the night has to be skipped instantly, because else the "Good Morning" message is not triggered and there will be only "Player stood up" messages for every player, that was laying in bed.

**Closed as not planned by GeheimagentNr1** 2023-11-21 20:32 UTC
Labels: enhancement
